# Generated by Django 4.0.3 on 2022-04-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monumentimage',
            name='img',
            field=models.ImageField(default='logo.png', upload_to='monuments/'),
        ),
        migrations.AddField(
            model_name='reportimage',
            name='img',
            field=models.ImageField(default='logo.png', upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.ImageField(default='logo.png', upload_to='uploads/'),
        ),
    ]
